server:
  port: 8081

auth:
  enabled: true
  username-claim: "cognito:username"
  email-claim: "email"
  accepted-issuers:
    - name: cognito
      url: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_ka4APzVaT
      jwks-url: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_ka4APzVaT/.well-known/jwks.json

cognito:
  user-pool-id: eu-west-1_ka4APzVaT

notifications:
  from-address: notifications@piko.test
  location-published:
    subject-template: "Your location ${location_name} was published"
    body-template: classpath:/location-published-email.html

spring:
  application.name: piko-admin
  mail:
    host: localhost
    port: 1025
  datasource:
    url: jdbc:postgresql://localhost:5432/piko_admin
    username: piko_admin
    password: piko_admin
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      default:
        contentType: application/json
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        location-events-out:
          destination: location-events
          group: piko-admin
        location-events-in:
          destination: location-events
          group: piko-admin

logging:
  level:
    com.bluesoft: debug
    org.apache.kafka.clients.consumer.ConsumerConfig: error
    org.apache.kafka.clients.producer.ProducerConfig: error
    org.apache.kafka.clients.admin.AdminClientConfig: error